---

- name: Check if a keystore exists
  command: docker exec elasticsearch test -f /usr/share/elasticsearch/config/elasticsearch.keystore
  register: result
  ignore_errors: true
  

- name: Create elasticsearch keystore
  command: /usr/share/elasticsearch/bin/elasticsearch-keystore create
  when: result.rc != 0
