---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint --config-file molecule/default/yamllint.yml .
  ansible-lint -c molecule/default/ansible-lint.yml .
  flake8
platforms:
  - name: "${MOLECULE_INSTANCE_NAME:-docker-ubuntu2004-ansible}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    published_ports:
      - '9200:9200/tcp'
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  options:
    vvv: true
  env:
    IN_MOLECULE: 'true'
scenario:
  name: default
verifier:
  name: ansible